#!/bin/bash

# ex: ./run.sh [-s] <repo_dir> <binary>


# reset
reset="\e[0m"       # Text Reset

# Regular Colors
black="\e[30m"        # Black
red='\e[31m'          # Red
green="\e[32m"        # Green
yellow='\e[33m'       # Yellow
blue='\e[34m'         # Blue
purple='\e[35m'       # Purple
cyan='\e[36m'         # Cyan
white='\e[37m'        # White

QUIET_MODE="1"
USAGE="usage:\t$0 -d <project_dir> -c <command> |\n\t$0 -d <project_dir> -b <binary_filename>"
ARGS=("$@")


# while true; do
#   case "$1" in
#     -v | --verbose ) QUIET_MODE="0"; shift ;;
#     -d | --dir ) PROJECT_DIR=$2; shift 2 ;;
#     -b | --bin ) BIN_FILE="$2"; shift 2 ;;
#     -c | --command ) COMMAND="$2"; shift 2 ;;
#     -- ) shift; break ;;
#     * ) break ;;
#   esac
# done
# echo $QUIET_MODE $PROJECT_DIR $BIN_FILE "$COMMAND"

while getopts ":vd:c:b:" opt; do
  case $opt in
    v)
		printf -- '-v: verbose mode activated\n'
		QUIET_MODE="0"
		;;
	d)
    	PROJECT_DIR=$OPTARG
    	;;
	b)
		BIN_FILE=$OPTARG
		;;
	c)
		COMMAND=$OPTARG
		;;
    \?)
		printf "${red}invalid option: -$OPTARG\n${reset}" >&2
		echo -e $USAGE
		exit 1
		;;
    :)
		printf "${red}error: option -$OPTARG requires an argument\n${reset}" >&2
		echo -e $USAGE
		exit 1
		;;
  esac
done

if [ "$QUIET_MODE" -eq "1" ]; then
	docker build -t valgrind42-img . > /dev/null
else
	docker build -t valgrind42-img .
fi

if [ -n "$PROJECT_DIR" ] && [ -n "$COMMAND" ]; then
	docker run -e QUIET_MODE=$QUIET_MODE -e COMMAND="$COMMAND" -v $(find $PWD -type d -name $(basename $PROJECT_DIR)):/root/repo -it valgrind42-img
elif [ -n "$PROJECT_DIR" ] && [ -n "$BIN_FILE" ]; then
	docker run -e QUIET_MODE=$QUIET_MODE -e BIN_FILE=$BIN_FILE -v $(find $PWD -type d -name $(basename $PROJECT_DIR)):/root/repo -it valgrind42-img 
else
	echo -e $USAGE
	exit 1
fi

# if echo $* | grep -e "-s" -q
# then
#   	docker build -t valgrind42-img . > /dev/null
# 	docker run -e BIN_FILE=$2 -v $(find $PWD -type d -name $(basename $1)):/root/repo -it valgrind42-img
# else
# 	docker build -t valgrind42-img .
# 	docker run -e "TERM=xterm-256color" -e BIN_FILE=$2 -v $(find $PWD -type d -name $(basename $1)):/root/repo -it valgrind42-img 
# fi

