#!/bin/bash

reset="\e[0m"
black="\e[30m"
red='\e[31m'
green="\e[32m"
yellow='\e[33m'
blue='\e[34m'
purple='\e[35m'
cyan='\e[36m'
white='\e[37m'

QUIET_MODE="1"
USAGE="usage:\t$0 -d <project_dir> -c <command> |\n\t$0 -d <project_dir> -b <binary_filename>\n\n"\
"-d : your project directory (absolute path required)\n"\
"-b : the filename of the binary target of your project's Makefile\n\n"\
"Warning: the Makefile in your project folder should:\n\t1) use the CC variable for compilation\n\t2) contain a rebuild rule \"re\"\n"

open -g -a Docker

while (! docker stats --no-stream > /dev/null 2>&1 ); do
  # docker takes a few seconds to initialize
	printf "${yellow}waiting for docker to launch...\n${reset}"
  	sleep 10
done

while getopts ":vd:c:b:" opt; do
  case $opt in
    v)
		printf -- '-v: verbose mode activated\n'
		QUIET_MODE="0"
		;;
	d)
    	PROJECT_DIR=$OPTARG
    	;;
	b)
		BIN_FILE=$OPTARG
		;;
	c)
		COMMAND=$OPTARG
		;;
    \?)
		printf "${red}invalid option: -$OPTARG\n\n${reset}" >&2
		echo -e $USAGE
		exit 1
		;;
    :)
		printf "${red}error: option -$OPTARG requires an argument\n\n${reset}" >&2
		echo -e $USAGE
		exit 1
		;;
  esac
done

# echo "QUIET_MODE = $QUIET_MODE"
# echo "PROJECT_DIR = $PROJECT_DIR"
# echo "BIN_FILE = $BIN_FILE"
# echo "QUIET_MODE = $QUIET_MODE"

if [[ ("$COMMAND" == "" && "$BIN_FILE" == "") || "$PROJECT_DIR" == "" ]] ; then
	printf "${red}error: missing required flag parameters${reset}\n\n"
	echo -e $USAGE
	exit 1
fi

if [ ! -d $PROJECT_DIR ]; then
	printf "${red}error: provided path for -d flag (project directory) does not exist${reset}\n\n"
	echo -e $USAGE
	exit 1
fi

if [[ "$PROJECT_DIR" != /* ]]; then
	printf "${red}error: provided path for -d flag (project directory) should be an absolute path${reset}\n\n"
	echo -e $USAGE
	exit 1
fi

printf "${green}building container image...${reset}\n"

if [ "$QUIET_MODE" -eq "1" ]; then
	docker build -t valgrind42-img . > /dev/null
else
	docker build -t valgrind42-img .
fi

printf "${green}running container...${reset}\n"

if [ -n "$PROJECT_DIR" ] && [ -n "$COMMAND" ]; then
	docker run -e QUIET_MODE=$QUIET_MODE -e COMMAND="$COMMAND" -v $PROJECT_DIR:/root/repo -it valgrind42-img
elif [ -n "$PROJECT_DIR" ] && [ -n "$BIN_FILE" ]; then
	docker run -e QUIET_MODE=$QUIET_MODE -e BIN_FILE=$BIN_FILE -v $PROJECT_DIR:/root/repo -it valgrind42-img 
else
	echo -e $USAGE
	exit 1
fi
